### ISSUE TITLE
WikidataSameAsExtractor makes wrong URLs when title has strange chars

### ISSUE THREAD

**Issue by VladimirAlexiev** [dbpedia/extraction-framework#405] opened 2015-08-07 12:45 UTC
These lines
```
<http://dbpedia.org/resource/%2522...The_Truth_Is_a_Fucking_Lie...%2522>
owl:sameAs <http://wikidata.dbpedia.org/resource/Q13416956>.
<http://dbpedia.org/resource/%2522...The_Truth_Is_a_Fucking_Lie...%2522>
owl:sameAs <http://wikidata.org/entity/Q13416956>.
```
come from en inter-language links in 2015-04 (Boyan extracted them). I assume they come from WikidataSameAsExtractor.

But the right way to render this URL is `http://dbpedia.org/page/%22...The_Truth_Is_a_Fucking_Lie...%22`.

As you can see on `http://dbpedia.org/page/%2522...The_Truth_Is_a_Fucking_Lie...%2522`, the sameAs statements are alone there.

The WikidataSameAsExtractor should use the same "make URL from title" function as all other extractors.

**Comment by jimkont** [comment] 2015-08-07 13:35
@VladimirAlexiev it does use the same function for the link, maybe the wikidata title links are decoded
@alismayilov can you take a look?

**Comment by VladimirAlexiev** [comment] 2015-08-07 14:27
The point is that the URLs coming out of DBpedia extractor are not consistent:
- http://dbpedia.org/page/%22...The_Truth_Is_a_Fucking_Lie...%22 : has most statements
- http://dbpedia.org/page/%2522...The_Truth_Is_a_Fucking_Lie...%2522 : has only WikidataSameAsExtractor statements

**Comment by jimkont** [comment] 2015-08-07 14:29
the other facts come out of the wikipedia dumps which are wikitext, the sameAs link come from the wikidata json dumps, my first impression is that in Wikidata dumps the titles are already decoded. 
will look further into that

**Comment by alismayilov** [comment] 2015-08-07 15:33
We parse it as a WikiTitle in sameAsExtractor. https://github.com/dbpedia/extraction-framework/blob/master/core/src/main/scala/org/dbpedia/extraction/mappings/wikidata/WikidataSameAsExtractor.scala#L45

I compared titles between wikidata xml and wikipedia xml. 
In wikidata xml there is additional character (\) to escape ", i.e. "sitelinks":{"enwiki":{"site":"enwiki","title":"\"...The Truth Is a Fucking Lie...\"","badges":[]}.
But in wikipedia xml, it is between title tag and it is without \. <title>"...The Truth Is a Fucking Lie..."</title>. 
@jimkont  I think the issue is how WikiTitle handles \?

**Comment by jimkont** [comment] 2015-08-08 13:18
" is decoded to %22 and when this is decoded (falsely) again results in %2522 (only % is decoded and which is %25)

`\"` should be  how json escapes `"` 
can you find the item in the xml dumps? maybe there is a bug there

**Comment by alismayilov** [comment] 2015-08-10 10:05
I think the bug is in WikiTitle class.  sitelink.encoded prints right encoding (%22...The_Truth_Is_a_Fucking_Lie...%22), but sitelink.resourceIri converts it to (http://en.dbpedia.org/resource/%2522...The_Truth_Is_a_Fucking_Lie...%2522). Somehow resourceIri decode it two times?

**Comment by alismayilov** [comment] 2015-08-10 16:01
The problem comes from this line: https://github.com/dbpedia/extraction-framework/blob/master/core/src/main/scala/org/dbpedia/extraction/wikiparser/WikiTitle.scala#L51

Append method escapes character https://github.com/dbpedia/extraction-framework/blob/master/core/src/main/scala/org/dbpedia/extraction/ontology/RdfNamespace.scala#L25 and therefore % conerted to %25. 

Workaround could be this: 
We can replace
 val sitelink = WikiTitle.parse(siteLink.getPageTitle(), dbpedia_lang) to 
val resourceIri= dbpedia_lang.resourceUri.append(siteLink.getPageTitle)

I tested and it works in this way. Shall commit it?

**Comment by jimkont** [comment] 2015-08-10 20:30
Yes, please do
I think I've seen this pattern somewhere else as well

**Comment by jimkont** [comment] 2015-08-11 12:15
Thanks @alismayilov 
I merged the PR

**Closed by jimkont** 2015-08-11 12:15 UTC
