### ISSUE TITLE
Kill loose pages masquerading as mappings

### ISSUE THREAD

**Issue by VladimirAlexiev** [dbpedia/extraction-framework#349] opened 2015-02-25 10:21 UTC
I searched for [templateProperty but not in any mapping](http://mappings.dbpedia.org/index.php?title=Special%3ASearch&redirs=1&search=templateproperty&fulltext=Search&ns0=1&ns10=1&ns11=1&ns200=1&ns201=1&ns202=1&ns203=1&ns206=1&ns207=1&redirs=1&title=Special%3ASearch&advanced=1&fulltext=Advanced+search). 
It returns 4 mappings: cs, ro, ro, ro

Related to https://github.com/dbpedia/mappings-tracker/issues/50

**Comment by jcsahnwaldt** [comment] 2015-02-25 11:40
When you click on the links in the search results, you will see that these pages don't exist or have been deleted. I think the search index hasn't been updated in a while. No relation to #314 .

**Comment by VladimirAlexiev** [comment] 2015-02-25 12:25
* Isn't it automatically updated? Surely when I added zodiacSign, it appeared in searches very soon.
* How do you explain the namespace restriction wasn't honored? Do you think these stray pages were moved between namespaces?

**Comment by jcsahnwaldt** [comment] 2015-02-25 18:08
I'm not sure. I think I saw similar problems a few years ago which disappeared after someone updated the index.

In the past, I've seen pages named Mapping_xy:Foo that someone had added before the namespace Mapping_xy actually existed. MediaWiki then treated the whole string "Mapping_xy:Foo" as the title of a page in the main namespace - colons are allowed in titles. Something like this may explain why these pages are listed in the search results.

But I'm not sure. Never dealt with the search index.

**Comment by jcsahnwaldt** [comment] 2015-02-25 20:02
I was wrong - it's not the index.

The problem is that there are a few pages in the main namespace that don't belong there. Their titles look like they are in other namespaces. They show up in searches and lists like http://mappings.dbpedia.org/index.php/Special:AllPages?namespace=0 , but it's hard to actually see their content - when you click the link, MediaWiki interprets their titles as if they were in another namespace and takes you that other page.

To see the content of these pages, you have to use the page ID. With the page IDs, we can also move the pages to their proper namespaces, and we could close this issue.

I think the only way to get the page IDs is through the API:

http://mappings.dbpedia.org/api.php?action=query&list=allpages&aplimit=500&apnamespace=0

Example:

The page http://mappings.dbpedia.org/index.php?curid=2501 is called `Mapping ca:Infotaula d'artista musical` (that's the title - `Mapping ca:` is part of the title string, not a namespace), but it's in the main namespace (probably because it was created before the namespace `Mapping ca` existed).

How do I know it's in the main namespace?
* The top left tab says "page"
* The links to the corresponding Wikipedia template and test exctraction are broken
* When I look at the HTML source, I see `wgNamespaceNumber=0`

The page http://mappings.dbpedia.org/index.php?curid=2992 is called `Infotaula_d'artista_musical`, but it's in the namespace `Mapping ca`, so its full title is also `Mapping ca:Infotaula d'artista musical`.

How do I know it's in the `Mapping ca` namespace?
* The top left tab says "mapping ca"
* The links to the corresponding Wikipedia template and test exctraction are OK
* When I look at the HTML source, I see `wgNamespaceNumber=226`

It's tricky: The full page titles look identical, but in the MediaWiki database, they are two completly different pages. When you click http://mappings.dbpedia.org/index.php/Mapping_ca:Infotaula_d'artista_musical (or any other link using the title), you will see the page in the `Mapping ca` namespace.

**Comment by jcsahnwaldt** [comment] 2015-02-25 20:42
Even with the page IDs, it's not easy to move the pages. Probably has to be done through http://mappings.dbpedia.org/api.php . Cumbersome... :-(

**Comment by VladimirAlexiev** [comment] 2015-03-03 18:13
Right you are! Here's the complete list:
     <p pageid="2497" ns="0" title="Mapping ca:Actor" />
      <p pageid="2495" ns="0" title="Mapping ca:Fitxa de pel·lícula" />
      <p pageid="2498" ns="0" title="Mapping ca:Infotaula Llibre" />
      <p pageid="2501" ns="0" title="Mapping ca:Infotaula d&#039;artista musical" />
      <p pageid="2500" ns="0" title="Mapping ca:Partit polític" />
      <p pageid="4541" ns="0" title="Mapping cs:Film infobox" />
      <p pageid="2494" ns="0" title="Mapping es:Ficha de película" />
      <p pageid="6541" ns="0" title="Mapping id:Infobox building" />
      <p pageid="2907" ns="0" title="Mapping nl:software" />
      <p pageid="2469" ns="0" title="Mapping pl:Aktor infobox" />
      <p pageid="2493" ns="0" title="Mapping pl:Film infobox" />
      <p pageid="2499" ns="0" title="Mapping pl:Książka infobox" />
      <p pageid="2492" ns="0" title="Mapping pl:Zwierzę infobox" />
      <p pageid="10110" ns="0" title="Mapping ro:Carte" />
      <p pageid="10111" ns="0" title="Mapping ro:Discografie" />
      <p pageid="10112" ns="0" title="Mapping ro:Papă" />

I don't think we need to move them but just kill them. They can't be edited in their current broken location, right?

**Comment by jcsahnwaldt** [comment] 2015-03-03 18:45
Some may contain useful mappings, so it might be better to move them... not sure...

I didn't find a way to edit them. You can get the edit page through URLs like curid=...&action=edit , but when you try to save, you'll get an error message, IIRC. Maybe there's a simple trick like editing the HTML of the edit page (e.g. in Chrome developer tools) before clicking save. I don't know.

Writing a script that goes through your list and makes two API calls for each page (one login, one move - or is there a simpler way?) wouldn't be very hard either. Maybe an hour of work, maybe two. But still...

**Comment by jcsahnwaldt** [comment] 2015-03-04 00:35
OK, I tried it - it's possible to move or delete these pages through the browser, but it's a nuisance.

I opened two tabs in Chrome, opened Deveoper Tools in both, went to http://mappings.dbpedia.org/index.php?curid=2501&action=edit in the first tab and to http://mappings.dbpedia.org/index.php?title=Mapping_ca:Infotaula_d'artista_musical&action=edit in the second. Looked through the source code, copied the value that looked like `20101231125959` of `<input type="hidden" value="20101231125959" name="wpEdittime">` from the second tab to the same spot in the first tab and clicked the save button in the first tab. This meant that the content of page curid=2501 was saved as the new content of page Mapping_ca:Infotaula_d'artista_musical . Whew.

Then I did something similar for deleting page 2501: Open one tab with Dev Tools. Go to http://mappings.dbpedia.org/index.php?curid=2501&action=delete . Change

    <form method="post" action="/index.php?title=Mapping_ca:Infotaula_d%27artista_musical&amp;action=delete" id="deleteconfirm">

to

    <form method="post" action="/index.php?curid=2501&amp;action=delete" id="deleteconfirm">

Done. Page 2501 is gone...

**Comment by jcsahnwaldt** [comment] 2015-03-04 01:04
I moved / deleted them all. Took half an hour. Oh well.

**Closed by jcsahnwaldt** 2015-03-04 01:04 UTC

**Comment by VladimirAlexiev** [comment] 2015-03-04 10:40
- I logged in by making a local file `api-login.html` (the login cookie is stored in my browser)
```html
<form method="POST" action="http://mappings.dbpedia.org/api.php">
<input type="hidden" name="action" value="login"/>
<input type="hidden" name="lgname" value="user"/>
<input type="hidden" name="lgpassword" value="password"/>
<input type="submit" name="submit"/>
</form>
```

Here's how to move:
- obtain a MOVE token:
http://mappings.dbpedia.org/api.php?action=query&prop=info&intoken=move&titles=Mapping+cs:Film+infobox
```xml
<page ns="224" title="Mapping cs:Film infobox" missing=""  starttimestamp="2015-03-04T10:14:29Z"
 movetoken="415af5fcXXXXXXXXXXXXXXXXXXX4d992e+\" />
```
- the token mentions ns=224 which is Mapping_cs (not ns=0 where the misplaced page actually is), but the token is universal
- so I can issue a MOVE by id:
http://mappings.dbpedia.org/api.php?action=move&fromid=4541&to=Mapping cs:Film infobox&token=XXXX&reason=move+to+correct+namespace&noredirect&watch
- however, I don't believe that page is needed. http://mappings.dbpedia.org/index.php?title=Special:Undelete&target=Mapping+cs%3AFilm+infobox&timestamp=20150304004500&diff=prev shows its text
- (Note: http://mappings.dbpedia.org/index.php?curid=4541&action=edit doesn't return anything)
- but this page is much richer: http://mappings.dbpedia.org/index.php/Mapping_cs:Infobox_film

So instead, I tried to delete
- obtained a DELETE token
http://mappings.dbpedia.org/api.php?action=query&prop=info&intoken=delete&titles=NOSUCH
```xml
<page ns="0" title="NOSUCH" missing="" starttimestamp="2015-03-04T10:28:12Z"
   deletetoken="415af5fXXXXXXXXXXXXd992e+\" />
```
- went to http://hurl.it and made a POST request like this:
http://mappings.dbpedia.org/api.php?action=delete&pageid=4541&token=415af5fXXXXXXXXXXXXd992e+\&reason=wrong+namespace&watch
- got error "You're not allowed to edit this wiki through the API"

Hmmm, the ending of these tokens looks doubtful to me: looks like badly escaped quote?

**Comment by VladimirAlexiev** [comment] 2015-03-04 10:42
Get the same error "You're not allowed to edit this wiki through the API" for MOVE as well. 
Tried removing a few chars from the end of the token, no luck.

**Comment by VladimirAlexiev** [comment] 2015-03-06 14:51
You did all this 3d ago! I guess I was asleep when writing my last 2 comments :-) Should teach me to refresh the browser before working on an issue. Thanks!
