### ISSUE TITLE
stuck in Building DBpedia Core Libraries 4.2-SNAPSHOT

### ISSUE THREAD

**Issue by yanghongquan** [dbpedia/extraction-framework#577] opened 2019-03-12 08:00 UTC
when run 'mvn clean install' in the root directory,program stuck in 

[INFO] --------------------< org.dbpedia.extraction:core >---------------------
[INFO] Building DBpedia Core Libraries 4.2-SNAPSHOT                       [2/7]
[INFO] --------------------------------[ jar ]---------------------------------
Downloading from www2.ph.ed.ac.uk-releases: http://www2.ph.ed.ac.uk/maven2/org/scalatest/scalatest_2.11/2.2.1/scalatest_2.11-2.2.1.pom

because the url is Unreachable......
so if anyone can tell me,how can solve this problem?thanks!!!
and my os is windows10

**Comment by JJ-Author** [comment] 2019-03-18 14:39
sorry we can not reproduce this problem. please try again and try to delete your maven cache first.

**Comment by kurzum** [comment] 2019-08-16 09:34
@yanghongquan cleaned my mvn cache and rebuilt on current master. 
Seems like you have an internet problem, we can't reproduce, closing

**Closed by kurzum** 2019-08-16 09:34 UTC
